### ISSUE TITLE
Add option to ignore child or empty tabs

### ISSUE THREAD

**Issue by ssokolow** [piroor/aggregate-tabs-to-main-window#3]
I have a triple-monitor Firefox setup like this...

![bitmap](https://user-images.githubusercontent.com/46915/45256657-99509a80-b367-11e8-8b7d-7568be9c7ae3.png)

...and it's very irritating when clicking a link in Thunderbird (or any other external application) causes one of my non-primary Firefox windows to change just because I interacted with it in a way which made Firefox think of it as "most recently used".

Since my primary window is a bit bigger than the others I tried installing this extension as a way to force externally opened tabs to appear in the primary window. However, I ran into another problem: It's too aggressive.

If I middle-click a tab, this extension overrules Tree Style Tab and forces it to the centre window. If I open a new blank tab, it forces it to the centre window. If I use a browser-provided menu entry like Addons or Preferences which would normally open in whichever window I used the menu to open it from, it forces it to the centre window.

Would you mind adding an option to only aggregate tabs with no existing window affinity (ie. externally opened tabs) and ignore ones that either certainly or probably have a window affinity (child tabs, new tabs, and `about:*`)?

**Comment by piroor** [comment]
Sadly it is very hard because WebExtensions API doesn't provide ability to know what is the exact trigger of a new tab. By the commit b8b6077 I've added ability to set exceptions for tabs opened from pinned and unpinned tabs, but currently it is impossible to set such exceptions for other detailed cases.

**Comment by ssokolow** [comment]
Then how does Tree Style Tab tell whether something is a child? I was just proposing this:

1. Use whatever mechanism TST uses to identify and ignore child tabs.
2. If necessary, defer moving the tab until the initial page being loaded can be determined.
3. If the initial page being loaded is one of the `about:...` pages, ignore it, since this is almost certainly something opened by a browser UI element which has a separate copy for each window. (eg. The New Tab button, the Add-ons or Preferences entries in the hamburger menu, etc.)

**Comment by piroor** [comment]
OK, I've added support for more type exceptions. There is a development build which is triable via "about:debugging": https://piro.sakura.ne.jp/xul/xpi/nightly/aggregate-tabs-to-main-window.xpi

**Comment by ssokolow** [comment]
I've got it installed (I'm on Developer Edition with extension signing disabled. I just clicked the link, OKed through as normal, and then went through the extra step of manually clicking "Enable".) but it's still behaving the same way as the release version.

How do I enable the new type exceptions?

**Comment by piroor** [comment]
Exceptions are configurable via the "preferences" page of the addon.

**Comment by ssokolow** [comment]
I guessed that much, but the only likely candidates are the fields which are revealed when "Debug mode" is selected and they're not intuitive enough for me to know how to change them to get the desired effect withour explanatory documentation.

**Comment by piroor** [comment]
Hmm, sorry it is my fault. The nighly build is not updated as I expected. Anyway, I've released a new version 1.3.0 and you'll see more options in the configuration page. For example, uncheck all checkboxes under "Tabs to be aggregated" except "All other cases" then tabs from non-existing tab (like tabs from external apps) will be moved automatically.

**Comment by ssokolow** [comment]
It's closer, but not perfect. If I do as you describe, the "New Tab" button and the Add-ons and Preferences menu entries still get aggregated.

If I do this, the "New Tab" button and Add-ons and Preferences menu entries don't get moved, but neither do the links I open from Thunderbird.

![screenshot16](https://user-images.githubusercontent.com/46915/45288994-0f651680-b4ba-11e8-9e25-bde4f29627de.png)

No matter what I try, the tab opened by clicking the "2 reviews" in the addon page still results in the tab being moved.

**Comment by piroor** [comment]
I've configured this addon exact same to the screenshot, and I got expected results - about:preferences, about:support, and about:addons are opened in a not largest window and stay there. Hmm...

Could you try logging? When the "Debug mode" checkbox is turned on, detailed logs will appear in the debugger's console for this addon. (You'll open the debugger console from about:debugging.)

**Comment by ssokolow** [comment]
The problem is that, when configured as shown in the screenshot, enabling the "Don't aggregate if it is matched to the regular expression" portion blocks the "Any other case" from working.

**Steps to Reproduce:**

1. Configure the extension as shown in the screenshot
1. Try clicking the "New Tab" button and the Addons and Preferences menu entries in a not-largest window.
1. Try running `firefox http://github.com/` in a terminal window.

**Expected:**

* The `about:*` pages (New Tab, Addons, Preferences) **should remain** in the window where the button or menu item was clicked.
* The externally-opened GitHub tab **should be moved** to the largest window.

**Actual behaviour:**

* The `about:*` pages (New Tab, Addons, Preferences) **remain** in the window where the button or menu item was clicked.
* The externally-opened GitHub tab **also remains** in the non-largest Window Firefox starts it in.

Today was distracting and It's late now so, if you still need the logging output, I'll get that tomorrow.

**Comment by piroor** [comment]
Sorry for this 2 years delay...

Today I researched again deeply and I've realized that tabs from external applications are opened with "about:blank" URL at first. Such a tab matches to the regular expression for "don't aggregate" and remained unexpectedly. So I've introduced some changes to detect really requested URLs.  With those changes, the case reported at the last comment works as expected for me now.
